Models/Shipper.cs
using Shipping.Models;
using Shipping.Models.Enums;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shipping.Models
{
	public class Shipper
	{
		[Key]
		public int Id { get; set; }

		[Required]
		[MaxLength(100)]
		[DisplayName("Họ tên")]
		public string Ten { get; set; } = null!;

		[Required]
		[Column(TypeName = "nvarchar(20)")]
		[DisplayName("CCCD")]
		public string CCCD { get; set; } = null!;

		[Required]
		[DisplayName("Giới tính")]
		public bool GioiTinh { get; set; }

		[Required]
		[Column(TypeName = "date")]
		[DisplayName("Ngày sinh")]
		[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
		public DateTime NgaySinh { get; set; }

		[Required]
		[Column(TypeName = "nvarchar(200)")]
		[DisplayName("Địa chỉ")]
		public string DiaChi { get; set; } = null!;

		[Required]
		public bool IsDeleted { get; set; } = false;

		[Required]
		[DisplayName("Loại shipper")]
		public LoaiShipper LoaiShipper { get; set; }

		[Required]
		[DisplayName("Trạng thái")]
		public TrangThaiShipper TrangThai { get; set; } = TrangThaiShipper.Nghi;

		[Required]
		[MaxLength(20)]
		[DisplayName("Biển số xe")]
		public string BienSoXe { get; set; } = null!;

		[MaxLength(500)]
		[DisplayName("Ảnh đại diện")]
		public string? HinhAnh { get; set; } = null!;

		[Column(TypeName = "nvarchar(max)")]
		public string? ViTri { get; set; }

		[DisplayName("Ngày cập nhật")]
		public DateTime NgayCapNhat { get; set; } = DateTime.Now;

		//Foreign Key
		[ForeignKey("User")]
		[DisplayName("Mã người dùng")]
		public string UserId { get; set; } = null!;
		public virtual IdentityUser User { get; set; } = null!;

		[ForeignKey("ChiNhanh")]
		[DisplayName("Chi nhánh")]
		public int? ChiNhanhId { get; set; }
		public virtual ChiNhanh? ChiNhanh { get; set; }

		[Required]
		[ForeignKey("TinhThanh")]
		[DisplayName("Tỉnh/Thành phố")]
		[Column(TypeName = "nvarchar(10)")]
		public string TinhThanhId { get; set; } = null!;
		public virtual TinhThanh TinhThanh { get; set; } = null!;

		[Required]
		[ForeignKey("PhuongXa")]
		[DisplayName("Phường/Xã")]
		[Column(TypeName = "nvarchar(10)")]
		public string PhuongXaId { get; set; } = null!;
		public virtual PhuongXa PhuongXa { get; set; } = null!;


		//Navigation
		public virtual ICollection<ChuyenHang> ChuyenHangs { get; set; } = null!;
	}
}

ViewModels/DashboardViewModel.cs
using Shipping.Models;

namespace Shipping.ViewModels
{
	public class DashboardViewModel
	{
		public int DonHangMoiHomNay { get; set; }
		public decimal DoanhThuHomNay { get; set; }
		public int DonHangChoXuLy { get; set; }
		public int ShipperDangBan { get; set; }


		public List<string> LabelsNgay { get; set; } = new List<string>();
		public List<decimal> DataDoanhThu { get; set; } = new List<decimal>();
		public List<int> DataDonHang { get; set; } = new List<int>();


		public int CountDaGiao { get; set; }
		public int CountDangGiao { get; set; }
		public int CountHuy { get; set; }


		public IEnumerable<DonHang> DonHangMoiNhat { get; set; } = new List<DonHang>();
	}
}

ViewModels/ShipperViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Shipping.Models.Enums;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Shipping.ViewModels
{
	public class ShipperViewModel
	{
		[Key]
		public int Id { get; set; }

		[Required(ErrorMessage = "Vui lòng nhập họ tên!")]
		[MaxLength(100)]
		[DisplayName("Họ tên")] // Cập nhật DisplayName
		public string Ten { get; set; } = null!; // Đã đổi từ HoTen sang Ten

		[Required(ErrorMessage = "Vui lòng nhập Email!")]
		[EmailAddress]
		[DisplayName("Email")]
		public string Email { get; set; } = null!;

		[Required(ErrorMessage = "Vui lòng nhập mật khẩu!")]
		[StringLength(100, ErrorMessage = "Mật khẩu phải dài ít nhất {2} và tối đa {1} ký tự.", MinimumLength = 6)]
		[DataType(DataType.Password)]
		[DisplayName("Mật khẩu")]
		[ValidateNever]
		public string Password { get; set; } = null!;

		[Required(ErrorMessage = "Vui lòng nhập CCCD!")]
		[MaxLength(20)]
		[DisplayName("CCCD")]
		public string CCCD { get; set; } = null!;

		[Required(ErrorMessage = "Vui lòng nhập số điện thoại!")]
		[MaxLength(20)]
		[DisplayName("Số điện thoại")]
		public string SDT { get; set; } = null!;

		[Required]
		[DisplayName("Giới tính")]
		public bool GioiTinh { get; set; }

		[Required(ErrorMessage = "Vui lòng nhập ngày sinh!")]
		[DataType(DataType.Date)]
		[DisplayName("Ngày sinh")]
		public DateTime NgaySinh { get; set; }

		[Required(ErrorMessage = "Vui lòng nhập địa chỉ!")]
		[DisplayName("Địa chỉ")]
		public string DiaChi { get; set; } = null!;

		[Required]
		[DisplayName("Tỉnh/Thành phố")]
		public string TinhThanhId { get; set; } = null!;

		[Required]
		[DisplayName("Phường/Xã")]
		public string PhuongXaId { get; set; } = null!;

		[Required]
		[DisplayName("Loại shipper")]
		public LoaiShipper LoaiShipper { get; set; }

		[Required]
		[DisplayName("Trạng thái")]
		public TrangThaiShipper TrangThai { get; set; } = TrangThaiShipper.Nghi;

		[Required]
		[MaxLength(20)]
		[DisplayName("Biển số xe")]
		public string BienSoXe { get; set; } = null!;

		[ValidateNever]
		[DisplayName("Ảnh đại diện")]
		public IFormFile? file { get; set; }

		[DisplayName("Chi nhánh")]
		public int? ChiNhanhId { get; set; }

		public bool IsDeleted { get; set; } = false;

		[ValidateNever]
		public string UserId { get; set; } = null!;

		public string? HinhAnh {  get; set; }
	}
}

Controllers/AddressController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shipping.Models;
using Shipping.Repositories.GeoService;

namespace Shipping.Controllers
{
	public class AddressController : Controller
	{
		private readonly IGeoService<PhuongXa> _phuongXaRepo;

		public AddressController(IGeoService<PhuongXa> phuongXaService)
		{
			_phuongXaRepo = phuongXaService;
		}

		[HttpGet]
		public IActionResult GetPhuongXaByTinhThanh(string tinhThanhId)
		{
			Console.WriteLine("Address Controller Woring!");
			if (string.IsNullOrEmpty(tinhThanhId))
			{
				return Json(new List<SelectListItem>());
			}

			var phuongXaList = _phuongXaRepo.GetAll()
											.Where(p => p.TinhThanhId == tinhThanhId)
											.Select(p => new
											{
												id = p.Id,
												name = p.TenPhuongXa
											})
											.ToList();

			return Json(phuongXaList);
		}
	}
}

Controllers/ShipperController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shipping.Data;
using Shipping.Models;
using Shipping.Models.Enums;
using Shipping.Repositories.CrudService;
using Shipping.Repositories.DonHangService;
using Shipping.Repositories.GeoService;
using Shipping.Repositories.UserService;
using Shipping.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shipping.Controllers
{
    public class ShipperController : Controller
    {
		private readonly UserManager<IdentityUser> _userManager;
		private readonly IShipperService _shipperRepo;
		private readonly IChuyenHangService _chuyenHangRepo;
		private readonly ICrudService<ChiNhanh> _chiNhanhRepo;
		private readonly IGeoService<TinhThanh> _tinhThanhRepo;
		private readonly IGeoService<PhuongXa> _phuongXaRepo;

		public ShipperController(UserManager<IdentityUser> userManager,
								 IShipperService shipperRepo,
								 IChuyenHangService chuyenHangRepo,
								 ICrudService<ChiNhanh> chiNhanhRepo,
								 IGeoService<TinhThanh> tinhThanhRepo,
								 IGeoService<PhuongXa> phuongXaRepo)
        {
			_userManager = userManager;
			_shipperRepo = shipperRepo;
			_chuyenHangRepo = chuyenHangRepo;
			_chiNhanhRepo = chiNhanhRepo;
			_tinhThanhRepo = tinhThanhRepo;
			_phuongXaRepo = phuongXaRepo;
		}

		public void GetData()
		{
			ViewBag.TinhThanh = _tinhThanhRepo.GetAll();
			ViewBag.PhuongXa = _phuongXaRepo.GetAll();
			ViewBag.ChiNhanh = _chiNhanhRepo.GetAll();
		}

		// GET: Shipper
		[Authorize(Roles = "Admin")]
		public IActionResult Index(string searchString)
        {
			ViewBag.Search = searchString;
			var shipper = _shipperRepo.GetAllActive();

			if (!string.IsNullOrEmpty(searchString))
			{
				searchString = searchString.ToLower();

				shipper = shipper.Where(s =>
					s.Ten.ToLower().Contains(searchString) ||
					s.User.PhoneNumber.Contains(searchString) ||
					s.User.Email.ToLower().Contains(searchString) ||
					s.BienSoXe.ToLower().Contains(searchString)
				);
			}

			GetData();
			return View(shipper);
		}

		// GET: Shipper/Details/5
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Details(int? id)
        {
			if (id == null)
			{
				return BadRequest();
			}
			var shipper = await _shipperRepo.GetById(id);
			if (shipper == null)
				return NotFound();

			var model = new ShipperViewModel()
			{
				Id = shipper.Id,
				UserId = shipper.UserId,
				Email = shipper.User.Email,
				Ten = shipper.Ten,
				SDT = shipper.User.PhoneNumber,
				CCCD = shipper.CCCD,
				NgaySinh = shipper.NgaySinh,
				GioiTinh = shipper.GioiTinh,
				TinhThanhId = shipper.TinhThanhId,
				PhuongXaId = shipper.PhuongXaId,
				DiaChi = shipper.DiaChi,
				ChiNhanhId = shipper.ChiNhanhId,
				LoaiShipper = shipper.LoaiShipper,
				BienSoXe = shipper.BienSoXe,
				HinhAnh = shipper.HinhAnh,
				IsDeleted = shipper.IsDeleted
			};

			ViewBag.TenTinhThanh = shipper.TinhThanh.TenTinhThanh;
			ViewBag.TenPhuongXa = shipper.PhuongXa.TenPhuongXa;
			ViewBag.TenChiNhanh = shipper.ChiNhanh != null ? shipper.ChiNhanh.TenChiNhanh : null;
			return View(model);
		}

		// GET: Shipper/Create
		[Authorize(Roles = "Admin")]
		public IActionResult Create()
        {
			GetData();
			return View(new ShipperViewModel());
		}

        // POST: Shipper/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Create(ShipperViewModel shipper)
        {
			if (!ModelState.IsValid)
			{
				GetData();
				return View(shipper);
			}
			var result = await _shipperRepo.Create(shipper);
			if (!result.Completed)
			{
				ModelState.AddModelError(String.Empty, result.Message);
				GetData();
				return View(shipper);
			}
			return RedirectToAction(nameof(Index));
        }

		// GET: Shipper/Edit/5
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int? id)
        {
			if (id == null)
			{
				return BadRequest();
			}
			var shipper = await _shipperRepo.GetById(id);
			if (shipper == null)
				return NotFound();
			var model = new ShipperViewModel()
			{
				Id = shipper.Id,
				UserId = shipper.UserId,
				Email = shipper.User.Email,
				Ten = shipper.Ten,
				SDT = shipper.User.PhoneNumber,
				CCCD = shipper.CCCD,
				NgaySinh = shipper.NgaySinh,
				GioiTinh = shipper.GioiTinh,
				TinhThanhId = shipper.TinhThanhId,
				PhuongXaId = shipper.PhuongXaId,
				DiaChi = shipper.DiaChi,
				ChiNhanhId = shipper.ChiNhanhId,
				LoaiShipper = shipper.LoaiShipper,
				BienSoXe = shipper.BienSoXe,
				HinhAnh = shipper.HinhAnh,
				IsDeleted = shipper.IsDeleted
			};
			GetData();
			return View(model);
        }

        // POST: Shipper/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(ShipperViewModel shipper)
        {
			if (!ModelState.IsValid)
			{
				GetData();
				return View(shipper);
			}

			var result = await _shipperRepo.Edit(shipper);
			if (!result.Completed)
			{
				ModelState.AddModelError(String.Empty, result.Message);
				GetData();
				return View(shipper);
			}
			return RedirectToAction(nameof(Index));
		}

        public async Task<IActionResult> Delete(int? id)
        {
			if (id == null)
			{
				return BadRequest();
			}

			var result = await _shipperRepo.Delete(id);
			if (!result.Completed)
				Console.WriteLine(result.Message);
			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[Authorize(Roles = "Shipper")]
		public async Task<IActionResult> UpdateState(string viTri, int trangThai)
		{
			var userId = _userManager.GetUserId(User);
			var result = await _shipperRepo.UpdateState(userId, viTri, trangThai);

			return Json(new { success = result.Completed, msg = result.Message });
		}

		[HttpGet]
		[Authorize(Roles = "Admin, NhanVien")]
		public async Task<IActionResult> GetAvailableShippers(string locationId)
		{
			var shippers = await _shipperRepo.GetAvailableShippers(locationId);
			return Json(shippers);
		}

		[Authorize(Roles = "Shipper")]
		public async Task<IActionResult> Dashboard()
		{
			var userId = _userManager.GetUserId(User);
			var shipper = await _shipperRepo.GetByUserId(userId);

			if (shipper == null) return RedirectToAction("AccessDenied", "Account", new { area = "Identity" });

			ViewBag.ListTinhThanh = new SelectList(_tinhThanhRepo.GetAll(), "Id", "TenTinhThanh", shipper.ViTri); 

			return View(shipper);
		}

		[HttpGet]
		[Authorize(Roles = "Admin,NhanVien")]
		public async Task<IActionResult> ResolveLocation(int type, string? dataId, string? orderId)
		{
			// type: 3 (Chi nhánh), 4 (Tiếp nối)
			string? locationId = null;

			// Type 3: Chi nhánh
			if (type == 3 && int.TryParse(dataId, out int cnId))
			{
				var chiNhanh = await _chiNhanhRepo.GetById(cnId);
				locationId = chiNhanh?.TinhThanhId;
			}
			// Type 4: Tiếp nối
			else if (type == 4 && !string.IsNullOrEmpty(orderId))
			{
				locationId = await _chuyenHangRepo.GetLastShipmentLocation(orderId);
			}

			return Json(new { locationId = locationId });
		}



	}
}

Views/Shipper/Edit.cshtml
@using Shipping.Models.Enums
@model Shipping.ViewModels.ShipperViewModel

@{
    ViewData["Title"] = "Cập nhật Shipper";
}

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-warning text-dark py-3">
                    <h4 class="mb-0 fw-bold text-center"><i class="fas fa-user-edit me-2"></i>Cập nhật thông tin Shipper</h4>
                </div>
                <div class="card-body p-4">
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                        <input asp-for="Id" type="hidden" />
                        <input asp-for="UserId" type="hidden" />
                        <input asp-for="HinhAnh" type="hidden" /> <div class="row">
                            <div class="col-md-3 text-center mb-4 mb-md-0 border-end">
                                <h6 class="fw-bold text-muted mb-3">Ảnh đại diện</h6>
                                <div class="mb-3">
                                    <img src="~/images/avatar/shipper/@Model.HinhAnh" id="HinhAnhPreview"
                                         class="rounded-circle shadow border p-1"
                                         style="width: 180px; height: 180px; object-fit: cover;"
                                         onerror="this.onerror=null;this.src='/images/avatar/default_image.jpg';" />
                                </div>
                                <div class="d-grid px-3">
                                    <label class="btn btn-outline-warning btn-sm">
                                        <i class="fas fa-camera me-1"></i> Đổi ảnh
                                        <input type="file" asp-for="file" class="d-none" onchange="previewImage(this)" accept="image/*" />
                                    </label>
                                </div>
                            </div>

                            <div class="col-md-9 ps-md-4">

                                <h6 class="text-primary fw-bold text-uppercase border-bottom pb-2 mb-3">
                                    <i class="fas fa-info-circle me-1"></i> Thông tin cơ bản
                                </h6>
                                <div class="row g-2 mb-3">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input asp-for="Ten" class="form-control" placeholder="Họ tên" />
                                            <label asp-for="Ten"></label>
                                            <span asp-validation-for="Ten" class="text-danger small"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input asp-for="Email" class="form-control" readonly style="background-color: #e9ecef;" />
                                            <label asp-for="Email"></label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input asp-for="CCCD" class="form-control" placeholder="CCCD" />
                                            <label asp-for="CCCD"></label>
                                            <span asp-validation-for="CCCD" class="text-danger small"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input asp-for="SDT" class="form-control" placeholder="SĐT" />
                                            <label asp-for="SDT"></label>
                                            <span asp-validation-for="SDT" class="text-danger small"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input asp-for="NgaySinh" class="form-control" type="date" />
                                            <label asp-for="NgaySinh"></label>
                                            <span asp-validation-for="NgaySinh" class="text-danger small"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pt-2">
                                        <div class="border rounded p-2 h-100 d-flex align-items-center">
                                            <label class="fw-bold small me-3 mb-0">Giới tính:</label>
                                            <div class="form-check form-check-inline mb-0">
                                                <input class="form-check-input" type="radio" asp-for="GioiTinh" value="true">
                                                <label class="form-check-label">Nam</label>
                                            </div>
                                            <div class="form-check form-check-inline mb-0">
                                                <input class="form-check-input" type="radio" asp-for="GioiTinh" value="false">
                                                <label class="form-check-label">Nữ</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <h6 class="text-primary fw-bold text-uppercase border-bottom pb-2 mb-3 mt-4">
                                    <i class="fas fa-map-marker-alt me-1"></i> Địa chỉ
                                </h6>
                                <div class="row g-2 mb-3">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <select asp-for="TinhThanhId" class="form-select">
                                                <option value="">-- Chọn Tỉnh/Thành --</option>
                                                @foreach (var t in (IEnumerable<TinhThanh>)ViewBag.TinhThanh)
                                                {
                                                    <option value="@t.Id">@t.TenTinhThanh</option>
                                                }
                                            </select>
                                            <label asp-for="TinhThanhId"></label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <select asp-for="PhuongXaId" class="form-select">
                                                <option value="">-- Phường/Xã --</option>
                                            </select>
                                            <label asp-for="PhuongXaId"></label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <input asp-for="DiaChi" class="form-control" placeholder="Địa chỉ" />
                                            <label asp-for="DiaChi"></label>
                                        </div>
                                    </div>
                                </div>

                                <h6 class="text-primary fw-bold text-uppercase border-bottom pb-2 mb-3 mt-4">
                                    <i class="fas fa-briefcase me-1"></i> Công việc
                                </h6>
                                <div class="row g-2">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <select asp-for="LoaiShipper" class="form-select" asp-items="Html.GetEnumSelectList<LoaiShipper>()"></select>
                                            <label asp-for="LoaiShipper"></label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <select asp-for="ChiNhanhId" class="form-select">
                                                <option value="">-- Chọn Chi nhánh --</option>
                                                @foreach (var t in (IEnumerable<ChiNhanh>)ViewBag.ChiNhanh)
                                                {
                                                    <option value="@t.Id">@t.TenChiNhanh</option>
                                                }
                                            </select>
                                            <label asp-for="ChiNhanhId"></label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input asp-for="BienSoXe" class="form-control" placeholder="Biển số xe" />
                                            <label asp-for="BienSoXe"></label>
                                            <span asp-validation-for="BienSoXe" class="text-danger small"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="d-flex justify-content-center mt-2">
                                            <a asp-action="Index" class="btn btn-secondary">
                                                <i class="fas fa-arrow-left me-1"></i> Hủy
                                            </a>
                                            &nbsp;
                                            <button type="submit" class="btn btn-warning fw-bold px-4 text-dark">
                                                <i class="fas fa-check-circle me-1"></i> Cập nhật
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function previewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#HinhAnhPreview').attr('src', e.target.result).show();
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(document).ready(function () {
            var selectedMaPhuongXa = '@Model?.PhuongXaId';

            $('#TinhThanhId').change(function () {
                var tinhThanhId = $(this).val();
                loadPhuongXa(tinhThanhId);
            });

            function loadPhuongXa(TinhThanhId) {
                var ddlPhuongXa = $('#PhuongXaId');
                ddlPhuongXa.empty().append('<option value="">-- Đang tải... --</option>');

                if (!TinhThanhId) {
                    ddlPhuongXa.empty().append('<option value="">-- Chọn Phường/Xã --</option>');
                    return;
                }

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetPhuongXaByTinhThanh", "Address")',
                    data: { TinhThanhId: TinhThanhId },
                    success: function (data) {
                        ddlPhuongXa.empty().append('<option value="">-- Chọn Phường/Xã --</option>');
                        $.each(data, function (index, item) {
                            ddlPhuongXa.append($('<option></option>').val(item.id).text(item.name));
                        });
                        if (selectedMaPhuongXa) {
                            ddlPhuongXa.val(selectedMaPhuongXa);
                            selectedMaPhuongXa = null;
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error("Lỗi khi tải Phường Xã:", error);
                        ddlPhuongXa.empty().append('<option value="">Lỗi tải dữ liệu</option>');
                    }
                });
            }

            var initialTinh = $('#TinhThanhId').val();
            if (initialTinh) {
                loadPhuongXa(initialTinh);
            }
        });
    </script>
}